const net = require("net");
const crypto = require("crypto");
const { db } = require("./db");
const { deleteLocalUpload, saveLocalEncryptedUpload } = require("./storage");

const GEO_CACHE_MAX_AGE_MS = 24 * 60 * 60 * 1000;
const geoCache = new Map();
let schemaPromise = null;

function ensureGameRecordSchema() {
  if (!schemaPromise) {
    schemaPromise = db.run(`
      CREATE TABLE IF NOT EXISTS game_records (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        game text NOT NULL,
        user_id bigint REFERENCES users(id) ON DELETE SET NULL,
        username text NOT NULL DEFAULT '',
        ip_address text NOT NULL,
        ip_location text NOT NULL DEFAULT '',
        latitude double precision,
        longitude double precision,
        location_accuracy double precision,
        location_recorded_at bigint,
        photo_url text NOT NULL DEFAULT '',
        photo_recorded_at bigint,
        user_agent text NOT NULL DEFAULT '',
        created_at bigint NOT NULL
      )
    `).then(() => db.run(`
      ALTER TABLE game_records
        ADD COLUMN IF NOT EXISTS latitude double precision,
        ADD COLUMN IF NOT EXISTS longitude double precision,
        ADD COLUMN IF NOT EXISTS location_accuracy double precision,
        ADD COLUMN IF NOT EXISTS location_recorded_at bigint,
        ADD COLUMN IF NOT EXISTS photo_url text NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS photo_recorded_at bigint
    `)).then(() => db.run(`
      CREATE INDEX IF NOT EXISTS game_records_created_at_idx
      ON game_records(created_at DESC)
    `)).then(() => db.run(`
      DELETE FROM game_records duplicate
      USING game_records original
      WHERE duplicate.id > original.id
        AND duplicate.game = original.game
        AND duplicate.ip_address = original.ip_address
        AND (duplicate.created_at / 60000) = (original.created_at / 60000)
    `)).then(() => db.run(`
      CREATE UNIQUE INDEX IF NOT EXISTS game_records_game_ip_minute_idx
      ON game_records(game, ip_address, ((created_at / 60000)))
    `));
  }

  return schemaPromise;
}

function normalizeIp(ipAddress) {
  return String(ipAddress || "")
    .trim()
    .replace(/^::ffff:/, "")
    .replace(/^\[|\]$/g, "");
}

function getRequestIp(req) {
  const forwardedFor = String(req.headers["x-forwarded-for"] || "")
    .split(",")
    .map(normalizeIp)
    .find(Boolean);
  const realIp = normalizeIp(req.headers["x-real-ip"]);

  return normalizeIp(forwardedFor || realIp || req.socket?.remoteAddress || req.ip || "");
}

function isPrivateIp(ipAddress) {
  if (!ipAddress) {
    return true;
  }

  if (ipAddress === "localhost" || ipAddress === "::1" || ipAddress === "127.0.0.1") {
    return true;
  }

  if (net.isIPv4(ipAddress)) {
    const [first, second] = ipAddress.split(".").map(Number);
    return (
      first === 10 ||
      (first === 172 && second >= 16 && second <= 31) ||
      (first === 192 && second === 168) ||
      first === 127
    );
  }

  if (net.isIPv6(ipAddress)) {
    const lowerIp = ipAddress.toLowerCase();
    return lowerIp === "::1" || lowerIp.startsWith("fc") || lowerIp.startsWith("fd");
  }

  return false;
}

function formatIpLocation(geo) {
  const parts = [geo.city, geo.regionName, geo.country].filter(Boolean);
  return parts.join(", ") || "Unknown";
}

async function lookupIpLocation(ipAddress) {
  if (isPrivateIp(ipAddress)) {
    return "Local / Private network";
  }

  const cached = geoCache.get(ipAddress);
  if (cached && Date.now() - cached.cachedAt < GEO_CACHE_MAX_AGE_MS) {
    return cached.location;
  }

  try {
    const fields = "status,message,country,regionName,city,query";
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 2500);
    try {
      const response = await fetch(
        `http://ip-api.com/json/${encodeURIComponent(ipAddress)}?fields=${fields}&lang=zh-CN`,
        { signal: controller.signal },
      );

      if (!response.ok) {
        return "Unknown";
      }

      const geo = await response.json();
      const location = geo.status === "success" ? formatIpLocation(geo) : (geo.message || "Unknown");

      geoCache.set(ipAddress, {
        cachedAt: Date.now(),
        location,
      });

      return location;
    } finally {
      clearTimeout(timeoutId);
    }
  } catch (error) {
    console.error("IP location lookup failed:", error.message);
    return "Unknown";
  }
}

function serializeRecord(row) {
  const userAgent = row.user_agent || "";

  return {
    id: row.id,
    game: row.game,
    username: row.username || "Guest",
    ipAddress: row.ip_address,
    ipLocation: row.ip_location || "Unknown",
    latitude: row.latitude,
    longitude: row.longitude,
    locationAccuracy: row.location_accuracy,
    locationRecordedAt: row.location_recorded_at,
    photoUrl: row.photo_url || "",
    photoRecordedAt: row.photo_recorded_at,
    browser: parseBrowser(userAgent),
    userAgent,
    createdAt: row.created_at,
  };
}

function parseBrowser(userAgent) {
  const text = String(userAgent || "");

  if (!text) {
    return "Unknown";
  }

  if (text.includes("MicroMessenger")) {
    return "WeChat / 微信";
  }

  if (text.includes("Edg/")) {
    return "Edge";
  }

  if (text.includes("OPR/") || text.includes("Opera")) {
    return "Opera";
  }

  if (text.includes("Firefox/")) {
    return "Firefox";
  }

  if (text.includes("SamsungBrowser/")) {
    return "Samsung Internet";
  }

  if (text.includes("Chrome/") || text.includes("CriOS/")) {
    return "Chrome";
  }

  if (text.includes("Safari/")) {
    return "Safari";
  }

  return "Unknown";
}

function readCoordinate(value, min, max) {
  const coordinate = Number(value);

  if (!Number.isFinite(coordinate) || coordinate < min || coordinate > max) {
    return null;
  }

  return coordinate;
}

function readAccuracy(value) {
  const accuracy = Number(value);

  if (!Number.isFinite(accuracy) || accuracy < 0) {
    return null;
  }

  return accuracy;
}

function readRecordIds(value) {
  if (!Array.isArray(value)) {
    return [];
  }

  return [...new Set(value.map(Number))]
    .filter((id) => Number.isInteger(id) && id > 0)
    .slice(0, 200);
}

function readPhotoDataUrl(value) {
  const text = String(value || "");
  const match = text.match(/^data:image\/(jpeg|jpg|png|webp);base64,([a-zA-Z0-9+/=]+)$/);

  if (!match) {
    return null;
  }

  const buffer = Buffer.from(match[2], "base64");

  if (!buffer.length || buffer.length > 2 * 1024 * 1024) {
    return null;
  }

  const subtype = match[1] === "jpg" ? "jpeg" : match[1];

  return {
    buffer,
    contentType: `image/${subtype}`,
    extension: subtype === "jpeg" ? "jpg" : subtype,
  };
}

function registerGameRecordRoutes(app, { getRequestSession, requireSession }) {
  app.post("/api/game-records/tetris", async (req, res) => {
    await ensureGameRecordSchema();

    const session = await getRequestSession(req);
    const ipAddress = getRequestIp(req);
    const createdAt = Date.now();
    const ipLocation = await lookupIpLocation(ipAddress);
    const userAgent = String(req.headers["user-agent"] || "").slice(0, 500);
    const latitude = readCoordinate(req.body?.latitude, -90, 90);
    const longitude = readCoordinate(req.body?.longitude, -180, 180);
    const locationAccuracy = readAccuracy(req.body?.accuracy);
    const hasBrowserLocation = latitude !== null && longitude !== null;
    const locationRecordedAt = hasBrowserLocation ? createdAt : null;
    const photo = readPhotoDataUrl(req.body?.photoDataUrl);
    let photoUrl = "";
    let photoRecordedAt = null;

    if (photo) {
      const savedPhoto = await saveLocalEncryptedUpload({
        buffer: photo.buffer,
        contentType: photo.contentType,
        filename: `game-record-${createdAt}-${crypto.randomUUID()}.${photo.extension}`,
        kind: "image",
      });

      photoUrl = savedPhoto.dbUrl;
      photoRecordedAt = createdAt;
    }

    const currentMinute = Math.floor(createdAt / 60000);
    const existingRecord = photoUrl
      ? await db.get(`
        SELECT photo_url
        FROM game_records
        WHERE game = $1
          AND ip_address = $2
          AND (created_at / 60000) = $3
        LIMIT 1
      `, ["tetris", ipAddress || "Unknown", currentMinute])
      : null;

    const result = await db.run(`
      INSERT INTO game_records (
        game,
        user_id,
        username,
        ip_address,
        ip_location,
        latitude,
        longitude,
        location_accuracy,
        location_recorded_at,
        photo_url,
        photo_recorded_at,
        user_agent,
        created_at
      )
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
      ON CONFLICT (game, ip_address, ((created_at / 60000))) DO UPDATE SET
        user_id = COALESCE(game_records.user_id, excluded.user_id),
        username = CASE
          WHEN game_records.username = '' THEN excluded.username
          ELSE game_records.username
        END,
        latitude = COALESCE(excluded.latitude, game_records.latitude),
        longitude = COALESCE(excluded.longitude, game_records.longitude),
        location_accuracy = COALESCE(excluded.location_accuracy, game_records.location_accuracy),
        location_recorded_at = COALESCE(excluded.location_recorded_at, game_records.location_recorded_at),
        photo_url = CASE
          WHEN excluded.photo_url <> '' THEN excluded.photo_url
          ELSE game_records.photo_url
        END,
        photo_recorded_at = COALESCE(excluded.photo_recorded_at, game_records.photo_recorded_at)
      RETURNING xmax = 0 AS inserted
    `, [
      "tetris",
      session?.userId || null,
      session?.username || "",
      ipAddress || "Unknown",
      ipLocation,
      latitude,
      longitude,
      locationAccuracy,
      locationRecordedAt,
      photoUrl,
      photoRecordedAt,
      userAgent,
      createdAt,
    ]);

    if (photoUrl && existingRecord?.photo_url && existingRecord.photo_url !== photoUrl) {
      deleteLocalUpload(existingRecord.photo_url);
    }

    return res.json({
      deduped: !result.rows[0]?.inserted,
      ok: true,
      photoUrl,
    });
  });

  app.get("/api/game-records", async (req, res) => {
    const session = await requireSession(req, res);

    if (!session) {
      return;
    }

    await ensureGameRecordSchema();

    const records = await db.all(`
      SELECT
        id,
        game,
        username,
        ip_address,
        ip_location,
        latitude,
        longitude,
        location_accuracy,
        location_recorded_at,
        photo_url,
        photo_recorded_at,
        user_agent,
        created_at
      FROM game_records
      ORDER BY created_at DESC
      LIMIT 200
    `);

    return res.json({
      records: records.map(serializeRecord),
    });
  });

  app.delete("/api/game-records", async (req, res) => {
    const session = await requireSession(req, res);

    if (!session) {
      return;
    }

    await ensureGameRecordSchema();

    const ids = readRecordIds(req.body?.ids);

    if (!ids.length) {
      return res.status(400).json({
        message: "No records selected / 未选择记录",
      });
    }

    const records = await db.all("SELECT photo_url FROM game_records WHERE id = ANY($1::bigint[])", [ids]);
    const result = await db.run("DELETE FROM game_records WHERE id = ANY($1::bigint[])", [ids]);

    records.forEach((record) => {
      if (record.photo_url) {
        deleteLocalUpload(record.photo_url);
      }
    });

    return res.json({
      deletedCount: result.rowCount,
      ok: true,
    });
  });
}

module.exports = {
  registerGameRecordRoutes,
};
